function sl_customization(cm)
    cObj = cm.SimulinkRequirementsCustomizer;
    
    %% Safety Goals
    cObj.addCustomRequirementType('Safety Goal', ...
        slreq.custom.RequirementType.Functional, ...
        'Safety Goal');
    
    %% Functional Safety Requirement
    cObj.addCustomRequirementType('Functional Safety Requirement', ...
        slreq.custom.RequirementType.Functional, ...
        'Functional Safety Requirement');

    %% Technical Safety Requirements
    cObj.addCustomRequirementType('Technical Safety Requirement', ...
        slreq.custom.RequirementType.Functional, ...
        'Technical Safety Requirement');

    %% Software Requirements
    cObj.addCustomRequirementType('Software Functional', ...
        slreq.custom.RequirementType.Functional, ...
        'Software Functional');
    
    cObj.addCustomRequirementType('Software Property', ...
        slreq.custom.RequirementType.Functional, ...
        'Software Propery');
    
    cObj.addCustomRequirementType('Software Interface',...
        slreq.custom.RequirementType.Functional, ...
        'Software Interface Requirement');

    
    %% Hardware requirements
    cObj.addCustomRequirementType('Hardware', ...
        slreq.custom.RequirementType.Functional, ...
        'Hardware');
    
    cObj.addCustomRequirementType('Hardware Property', ...
        slreq.custom.RequirementType.Functional, ...
        'Hardware Propery');
    
    cObj.addCustomRequirementType('SW/HW Interface', ...
        slreq.custom.RequirementType.Functional, ...
        'SW/HW Interface');

    %% New Link Types
    cObj.addCustomLinkType('Satisfy', slreq.custom.LinkType.Verify,...
        'Satisfies','Satisfied by', 'Links to Verification objects');
    
    cObj.addCustomLinkType('Solve', slreq.custom.LinkType.Implement,...
        'Solves', 'Solved by', 'Solution links')
    
    cObj.addCustomLinkType('Fulfil', slreq.custom.LinkType.Implement,...
        'Fulfils', 'Fulfilled by', 'Fullfilment links')
    
    cObj.addCustomLinkType('Allocate', slreq.custom.LinkType.Relate, ...
        'Allocated from', 'Allocated to', 'Allocation links')
end
